import logging
import asyncio
from typing import List
from sqlalchemy.orm import Session
from app.db.models.user import User
from app.agents.job_discovery_agent import JobDiscoveryAgent
from app.agents.job_ranking_agent import JobRankingAgent
from app.db.models.job import Job
from app.db.models.resume import Resume
from app.db.models.application import Application, ApplicationStatus

logger = logging.getLogger(__name__)

class AgentOrchestrator:
    """
    The Central Loop of the Autonomous Platform.
    1. Scrapes new jobs.
    2. Ranks them against the user's primary resume.
    3. Triggers notifications if high-matching jobs are found.
    4. Automatically generates applications (saves them as SAVED/PENDING).
    """
    def __init__(self, db: Session):
        self.db = db
        self.discovery = JobDiscoveryAgent()
        self.ranking = JobRankingAgent()
        
    async def run_autonomous_loop(self, user_id: int):
        logger.info(f"Starting Autonomous Orchestration Loop for User {user_id}")
        user = self.db.query(User).filter(User.id == user_id).first()
        if not user:
            return
            
        resume = self.db.query(Resume).filter(Resume.user_id == user_id, Resume.is_primary == True).first()
        if not resume:
            resume = self.db.query(Resume).filter(Resume.user_id == user_id).first()
            if not resume:
                logger.warning(f"No resume found for User {user_id}. Halting loop.")
                return
                
        # 1. Discover
        discovered_jobs = self.discovery.run_discovery(
            query="Software Engineer", 
            location="Remote", 
            platforms=["linkedin", "indeed"], 
            limit=5
        )
        
        # Save to DB
        saved_jobs = []
        for dj in discovered_jobs:
            existing = self.db.query(Job).filter(Job.apply_url == dj.apply_url, Job.user_id == user_id).first()
            if not existing:
                db_job = Job(
                    user_id=user_id,
                    apply_url=dj.apply_url,
                    raw_text=dj.description,
                    title=dj.title,
                    company=dj.company,
                    location=dj.location,
                    parsed_data={}
                )
                self.db.add(db_job)
                saved_jobs.append(db_job)
                
        self.db.commit()
        
        # We need the IDs for ranking
        for job in saved_jobs:
            self.db.refresh(job)
            
        if not saved_jobs:
            logger.info("No new jobs discovered in this cycle.")
            return
            
        # 2. Mocking matching for orchestration loop
        mock_match = {job.id: 0.85 for job in saved_jobs}
        mock_ats = {job.id: 0.90 for job in saved_jobs}
        
        # 3. Rank
        ranked = self.ranking.rank_jobs(resume, saved_jobs, mock_match, mock_ats)
        
        # 4. Generate Applications for Top 3
        top_jobs = ranked[:3]
        for r_job in top_jobs:
            if r_job.total_score > 0.7:
                # Add to application queue
                app = Application(
                    user_id=user_id,
                    job_id=r_job.job_id,
                    resume_id=resume.id,
                    status=ApplicationStatus.SAVED,
                    notes=f"Auto-generated by Orchestrator. Score: {r_job.total_score}"
                )
                self.db.add(app)
                
                # Mock sending notification
                logger.info(f"NOTIFICATION: High-match job found! Job ID {r_job.job_id}")
                
        self.db.commit()
        logger.info(f"Orchestration Loop complete. Generated {len(top_jobs)} new Application drafts.")
